
uint64 timestamp		   		 # time since system start (microseconds)

float32[3] drag_acceleration_xyz   		 # drag acceleration estimation in world frame xyz

float32[3] drag_acceleration_xyz_filtered	 # filtered drag acceleration estimation in world frame xyz

float32[3] drag_acceleration_moment_body	 # drag acceleration moment in body frame

float32[3] acc_expected_xyz	  		 # acc expected world frame xyz

